spring:
  profiles:
    active: prod
  datasource:
    url: jdbc:mysql://localhost:3306/splitwise?autoReconnect=true&useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true
  main:
    allow-circular-references: true

  #  **************** Email Configuration Start *********************

  mail:
    host: smtp.gmail.com
    port: 587
    username: uic.21mca2200@gmail.com
    password: uwyttadstxtuxixe
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


  #  **************** Email Configuration End *******************

